// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: picobox.proto

package picobox

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentMessage is sent from the PicoBox Daemon to the Master.
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Metrics
	//	*AgentMessage_DeployResponse
	//	*AgentMessage_StopResponse
	//	*AgentMessage_ExecResponse
	//	*AgentMessage_ContainerLog
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_picobox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetMetrics() *NodeMetrics {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *AgentMessage) GetDeployResponse() *DeployResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_DeployResponse); ok {
			return x.DeployResponse
		}
	}
	return nil
}

func (x *AgentMessage) GetStopResponse() *StopResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_StopResponse); ok {
			return x.StopResponse
		}
	}
	return nil
}

func (x *AgentMessage) GetExecResponse() *ExecResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ExecResponse); ok {
			return x.ExecResponse
		}
	}
	return nil
}

func (x *AgentMessage) GetContainerLog() *ContainerLog {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ContainerLog); ok {
			return x.ContainerLog
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Metrics struct {
	Metrics *NodeMetrics `protobuf:"bytes,1,opt,name=metrics,proto3,oneof"`
}

type AgentMessage_DeployResponse struct {
	DeployResponse *DeployResponse `protobuf:"bytes,2,opt,name=deploy_response,json=deployResponse,proto3,oneof"`
}

type AgentMessage_StopResponse struct {
	StopResponse *StopResponse `protobuf:"bytes,3,opt,name=stop_response,json=stopResponse,proto3,oneof"`
}

type AgentMessage_ExecResponse struct {
	ExecResponse *ExecResponse `protobuf:"bytes,4,opt,name=exec_response,json=execResponse,proto3,oneof"`
}

type AgentMessage_ContainerLog struct {
	ContainerLog *ContainerLog `protobuf:"bytes,5,opt,name=container_log,json=containerLog,proto3,oneof"`
}

func (*AgentMessage_Metrics) isAgentMessage_Payload() {}

func (*AgentMessage_DeployResponse) isAgentMessage_Payload() {}

func (*AgentMessage_StopResponse) isAgentMessage_Payload() {}

func (*AgentMessage_ExecResponse) isAgentMessage_Payload() {}

func (*AgentMessage_ContainerLog) isAgentMessage_Payload() {}

type ContainerLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	LogLine       string                 `protobuf:"bytes,2,opt,name=log_line,json=logLine,proto3" json:"log_line,omitempty"`
	IsStderr      bool                   `protobuf:"varint,3,opt,name=is_stderr,json=isStderr,proto3" json:"is_stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerLog) Reset() {
	*x = ContainerLog{}
	mi := &file_picobox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerLog) ProtoMessage() {}

func (x *ContainerLog) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerLog.ProtoReflect.Descriptor instead.
func (*ContainerLog) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerLog) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerLog) GetLogLine() string {
	if x != nil {
		return x.LogLine
	}
	return ""
}

func (x *ContainerLog) GetIsStderr() bool {
	if x != nil {
		return x.IsStderr
	}
	return false
}

// MasterMessage is sent from the Master to the PicoBox Daemon.
type MasterMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MasterMessage_HeartbeatAck
	//	*MasterMessage_DeployRequest
	//	*MasterMessage_StopRequest
	//	*MasterMessage_ExecRequest
	Payload       isMasterMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterMessage) Reset() {
	*x = MasterMessage{}
	mi := &file_picobox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterMessage) ProtoMessage() {}

func (x *MasterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterMessage.ProtoReflect.Descriptor instead.
func (*MasterMessage) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{2}
}

func (x *MasterMessage) GetPayload() isMasterMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MasterMessage) GetHeartbeatAck() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *MasterMessage) GetDeployRequest() *ContainerSpec {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_DeployRequest); ok {
			return x.DeployRequest
		}
	}
	return nil
}

func (x *MasterMessage) GetStopRequest() *StopRequest {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_StopRequest); ok {
			return x.StopRequest
		}
	}
	return nil
}

func (x *MasterMessage) GetExecRequest() *ExecRequest {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_ExecRequest); ok {
			return x.ExecRequest
		}
	}
	return nil
}

type isMasterMessage_Payload interface {
	isMasterMessage_Payload()
}

type MasterMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatResponse `protobuf:"bytes,1,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type MasterMessage_DeployRequest struct {
	DeployRequest *ContainerSpec `protobuf:"bytes,2,opt,name=deploy_request,json=deployRequest,proto3,oneof"`
}

type MasterMessage_StopRequest struct {
	StopRequest *StopRequest `protobuf:"bytes,3,opt,name=stop_request,json=stopRequest,proto3,oneof"`
}

type MasterMessage_ExecRequest struct {
	ExecRequest *ExecRequest `protobuf:"bytes,4,opt,name=exec_request,json=execRequest,proto3,oneof"`
}

func (*MasterMessage_HeartbeatAck) isMasterMessage_Payload() {}

func (*MasterMessage_DeployRequest) isMasterMessage_Payload() {}

func (*MasterMessage_StopRequest) isMasterMessage_Payload() {}

func (*MasterMessage_ExecRequest) isMasterMessage_Payload() {}

// NodeMetrics represents the hardware health and usage of a PicoBox node.
type NodeMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hostname         string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CpuUsagePercent  float32                `protobuf:"fixed32,2,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsedBytes  uint64                 `protobuf:"varint,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes uint64                 `protobuf:"varint,4,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	DiskIoWait       float32                `protobuf:"fixed32,5,opt,name=disk_io_wait,json=diskIoWait,proto3" json:"disk_io_wait,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeMetrics) Reset() {
	*x = NodeMetrics{}
	mi := &file_picobox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetrics) ProtoMessage() {}

func (x *NodeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetrics.ProtoReflect.Descriptor instead.
func (*NodeMetrics) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{3}
}

func (x *NodeMetrics) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeMetrics) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *NodeMetrics) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *NodeMetrics) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *NodeMetrics) GetDiskIoWait() float32 {
	if x != nil {
		return x.DiskIoWait
	}
	return 0
}

// HeartbeatResponse contains acknowledgments or fast commands from the Master.
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_picobox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// ContainerSpec defines the limits and resources required to deploy a container.
type ContainerSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContainerId    string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	MemoryMaxBytes uint64                 `protobuf:"varint,2,opt,name=memory_max_bytes,json=memoryMaxBytes,proto3" json:"memory_max_bytes,omitempty"` // e.g. for cgroup memory.max
	CpuMaxQuota    uint32                 `protobuf:"varint,3,opt,name=cpu_max_quota,json=cpuMaxQuota,proto3" json:"cpu_max_quota,omitempty"`          // e.g. for cgroup cpu.max
	RootfsImageUrl string                 `protobuf:"bytes,4,opt,name=rootfs_image_url,json=rootfsImageUrl,proto3" json:"rootfs_image_url,omitempty"`  // url or path to the rootfs tarball
	Command        string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`                                        // command to execute inside the container
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContainerSpec) Reset() {
	*x = ContainerSpec{}
	mi := &file_picobox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSpec) ProtoMessage() {}

func (x *ContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSpec.ProtoReflect.Descriptor instead.
func (*ContainerSpec) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerSpec) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerSpec) GetMemoryMaxBytes() uint64 {
	if x != nil {
		return x.MemoryMaxBytes
	}
	return 0
}

func (x *ContainerSpec) GetCpuMaxQuota() uint32 {
	if x != nil {
		return x.CpuMaxQuota
	}
	return 0
}

func (x *ContainerSpec) GetRootfsImageUrl() string {
	if x != nil {
		return x.RootfsImageUrl
	}
	return ""
}

func (x *ContainerSpec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// DeployResponse indicates the result of a deployment attempt.
type DeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_picobox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{6}
}

func (x *DeployResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DeployResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeployResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// StopRequest asks the agent to terminate a specific container.
type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // e.g. SIGKILL instead of SIGTERM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_picobox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{7}
}

func (x *StopRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StopRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// StopResponse indicates the result of a stop operation.
type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_picobox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{8}
}

func (x *StopResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_picobox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{9}
}

func (x *ExecRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_picobox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{10}
}

func (x *ExecResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ExecResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_picobox_proto protoreflect.FileDescriptor

const file_picobox_proto_rawDesc = "" +
	"\n" +
	"\rpicobox.proto\x12\apicobox\"\xc9\x02\n" +
	"\fAgentMessage\x120\n" +
	"\ametrics\x18\x01 \x01(\v2\x14.picobox.NodeMetricsH\x00R\ametrics\x12B\n" +
	"\x0fdeploy_response\x18\x02 \x01(\v2\x17.picobox.DeployResponseH\x00R\x0edeployResponse\x12<\n" +
	"\rstop_response\x18\x03 \x01(\v2\x15.picobox.StopResponseH\x00R\fstopResponse\x12<\n" +
	"\rexec_response\x18\x04 \x01(\v2\x15.picobox.ExecResponseH\x00R\fexecResponse\x12<\n" +
	"\rcontainer_log\x18\x05 \x01(\v2\x15.picobox.ContainerLogH\x00R\fcontainerLogB\t\n" +
	"\apayload\"i\n" +
	"\fContainerLog\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x19\n" +
	"\blog_line\x18\x02 \x01(\tR\alogLine\x12\x1b\n" +
	"\tis_stderr\x18\x03 \x01(\bR\bisStderr\"\x94\x02\n" +
	"\rMasterMessage\x12A\n" +
	"\rheartbeat_ack\x18\x01 \x01(\v2\x1a.picobox.HeartbeatResponseH\x00R\fheartbeatAck\x12?\n" +
	"\x0edeploy_request\x18\x02 \x01(\v2\x16.picobox.ContainerSpecH\x00R\rdeployRequest\x129\n" +
	"\fstop_request\x18\x03 \x01(\v2\x14.picobox.StopRequestH\x00R\vstopRequest\x129\n" +
	"\fexec_request\x18\x04 \x01(\v2\x14.picobox.ExecRequestH\x00R\vexecRequestB\t\n" +
	"\apayload\"\xd1\x01\n" +
	"\vNodeMetrics\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12*\n" +
	"\x11cpu_usage_percent\x18\x02 \x01(\x02R\x0fcpuUsagePercent\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x04 \x01(\x04R\x10memoryTotalBytes\x12 \n" +
	"\fdisk_io_wait\x18\x05 \x01(\x02R\n" +
	"diskIoWait\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\xc4\x01\n" +
	"\rContainerSpec\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12(\n" +
	"\x10memory_max_bytes\x18\x02 \x01(\x04R\x0ememoryMaxBytes\x12\"\n" +
	"\rcpu_max_quota\x18\x03 \x01(\rR\vcpuMaxQuota\x12(\n" +
	"\x10rootfs_image_url\x18\x04 \x01(\tR\x0erootfsImageUrl\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\"r\n" +
	"\x0eDeployResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"F\n" +
	"\vStopRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"p\n" +
	"\fStopResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"J\n" +
	"\vExecRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"\x88\x01\n" +
	"\fExecResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage2U\n" +
	"\fAgentService\x12E\n" +
	"\x0eControlChannel\x12\x15.picobox.AgentMessage\x1a\x16.picobox.MasterMessage\"\x00(\x010\x01B6Z4github.com/henny-cho/picobox/internal/api/pb;picoboxb\x06proto3"

var (
	file_picobox_proto_rawDescOnce sync.Once
	file_picobox_proto_rawDescData []byte
)

func file_picobox_proto_rawDescGZIP() []byte {
	file_picobox_proto_rawDescOnce.Do(func() {
		file_picobox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_picobox_proto_rawDesc), len(file_picobox_proto_rawDesc)))
	})
	return file_picobox_proto_rawDescData
}

var file_picobox_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_picobox_proto_goTypes = []any{
	(*AgentMessage)(nil),      // 0: picobox.AgentMessage
	(*ContainerLog)(nil),      // 1: picobox.ContainerLog
	(*MasterMessage)(nil),     // 2: picobox.MasterMessage
	(*NodeMetrics)(nil),       // 3: picobox.NodeMetrics
	(*HeartbeatResponse)(nil), // 4: picobox.HeartbeatResponse
	(*ContainerSpec)(nil),     // 5: picobox.ContainerSpec
	(*DeployResponse)(nil),    // 6: picobox.DeployResponse
	(*StopRequest)(nil),       // 7: picobox.StopRequest
	(*StopResponse)(nil),      // 8: picobox.StopResponse
	(*ExecRequest)(nil),       // 9: picobox.ExecRequest
	(*ExecResponse)(nil),      // 10: picobox.ExecResponse
}
var file_picobox_proto_depIdxs = []int32{
	3,  // 0: picobox.AgentMessage.metrics:type_name -> picobox.NodeMetrics
	6,  // 1: picobox.AgentMessage.deploy_response:type_name -> picobox.DeployResponse
	8,  // 2: picobox.AgentMessage.stop_response:type_name -> picobox.StopResponse
	10, // 3: picobox.AgentMessage.exec_response:type_name -> picobox.ExecResponse
	1,  // 4: picobox.AgentMessage.container_log:type_name -> picobox.ContainerLog
	4,  // 5: picobox.MasterMessage.heartbeat_ack:type_name -> picobox.HeartbeatResponse
	5,  // 6: picobox.MasterMessage.deploy_request:type_name -> picobox.ContainerSpec
	7,  // 7: picobox.MasterMessage.stop_request:type_name -> picobox.StopRequest
	9,  // 8: picobox.MasterMessage.exec_request:type_name -> picobox.ExecRequest
	0,  // 9: picobox.AgentService.ControlChannel:input_type -> picobox.AgentMessage
	2,  // 10: picobox.AgentService.ControlChannel:output_type -> picobox.MasterMessage
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_picobox_proto_init() }
func file_picobox_proto_init() {
	if File_picobox_proto != nil {
		return
	}
	file_picobox_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Metrics)(nil),
		(*AgentMessage_DeployResponse)(nil),
		(*AgentMessage_StopResponse)(nil),
		(*AgentMessage_ExecResponse)(nil),
		(*AgentMessage_ContainerLog)(nil),
	}
	file_picobox_proto_msgTypes[2].OneofWrappers = []any{
		(*MasterMessage_HeartbeatAck)(nil),
		(*MasterMessage_DeployRequest)(nil),
		(*MasterMessage_StopRequest)(nil),
		(*MasterMessage_ExecRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_picobox_proto_rawDesc), len(file_picobox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_picobox_proto_goTypes,
		DependencyIndexes: file_picobox_proto_depIdxs,
		MessageInfos:      file_picobox_proto_msgTypes,
	}.Build()
	File_picobox_proto = out.File
	file_picobox_proto_goTypes = nil
	file_picobox_proto_depIdxs = nil
}
