// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: picobox.proto

package picobox

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentMessage is sent from the PicoBox Daemon to the Master.
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Metrics
	//	*AgentMessage_DeployResponse
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_picobox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetMetrics() *NodeMetrics {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *AgentMessage) GetDeployResponse() *DeployResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_DeployResponse); ok {
			return x.DeployResponse
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Metrics struct {
	Metrics *NodeMetrics `protobuf:"bytes,1,opt,name=metrics,proto3,oneof"`
}

type AgentMessage_DeployResponse struct {
	DeployResponse *DeployResponse `protobuf:"bytes,2,opt,name=deploy_response,json=deployResponse,proto3,oneof"`
}

func (*AgentMessage_Metrics) isAgentMessage_Payload() {}

func (*AgentMessage_DeployResponse) isAgentMessage_Payload() {}

// MasterMessage is sent from the Master to the PicoBox Daemon.
type MasterMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MasterMessage_HeartbeatAck
	//	*MasterMessage_DeployRequest
	Payload       isMasterMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterMessage) Reset() {
	*x = MasterMessage{}
	mi := &file_picobox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterMessage) ProtoMessage() {}

func (x *MasterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterMessage.ProtoReflect.Descriptor instead.
func (*MasterMessage) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{1}
}

func (x *MasterMessage) GetPayload() isMasterMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MasterMessage) GetHeartbeatAck() *HeartbeatResponse {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *MasterMessage) GetDeployRequest() *ContainerSpec {
	if x != nil {
		if x, ok := x.Payload.(*MasterMessage_DeployRequest); ok {
			return x.DeployRequest
		}
	}
	return nil
}

type isMasterMessage_Payload interface {
	isMasterMessage_Payload()
}

type MasterMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatResponse `protobuf:"bytes,1,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type MasterMessage_DeployRequest struct {
	DeployRequest *ContainerSpec `protobuf:"bytes,2,opt,name=deploy_request,json=deployRequest,proto3,oneof"`
}

func (*MasterMessage_HeartbeatAck) isMasterMessage_Payload() {}

func (*MasterMessage_DeployRequest) isMasterMessage_Payload() {}

// NodeMetrics represents the hardware health and usage of a PicoBox node.
type NodeMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hostname         string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CpuUsagePercent  float32                `protobuf:"fixed32,2,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsedBytes  uint64                 `protobuf:"varint,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes uint64                 `protobuf:"varint,4,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	DiskIoWait       float32                `protobuf:"fixed32,5,opt,name=disk_io_wait,json=diskIoWait,proto3" json:"disk_io_wait,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeMetrics) Reset() {
	*x = NodeMetrics{}
	mi := &file_picobox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetrics) ProtoMessage() {}

func (x *NodeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetrics.ProtoReflect.Descriptor instead.
func (*NodeMetrics) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{2}
}

func (x *NodeMetrics) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeMetrics) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *NodeMetrics) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *NodeMetrics) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *NodeMetrics) GetDiskIoWait() float32 {
	if x != nil {
		return x.DiskIoWait
	}
	return 0
}

// HeartbeatResponse contains acknowledgments or fast commands from the Master.
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_picobox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// ContainerSpec defines the limits and resources required to deploy a container.
type ContainerSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContainerId    string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	MemoryMaxBytes uint64                 `protobuf:"varint,2,opt,name=memory_max_bytes,json=memoryMaxBytes,proto3" json:"memory_max_bytes,omitempty"` // e.g. for cgroup memory.max
	CpuMaxQuota    uint32                 `protobuf:"varint,3,opt,name=cpu_max_quota,json=cpuMaxQuota,proto3" json:"cpu_max_quota,omitempty"`          // e.g. for cgroup cpu.max
	RootfsImageUrl string                 `protobuf:"bytes,4,opt,name=rootfs_image_url,json=rootfsImageUrl,proto3" json:"rootfs_image_url,omitempty"`  // url or path to the rootfs tarball
	Command        string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`                                        // command to execute inside the container
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContainerSpec) Reset() {
	*x = ContainerSpec{}
	mi := &file_picobox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSpec) ProtoMessage() {}

func (x *ContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSpec.ProtoReflect.Descriptor instead.
func (*ContainerSpec) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerSpec) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerSpec) GetMemoryMaxBytes() uint64 {
	if x != nil {
		return x.MemoryMaxBytes
	}
	return 0
}

func (x *ContainerSpec) GetCpuMaxQuota() uint32 {
	if x != nil {
		return x.CpuMaxQuota
	}
	return 0
}

func (x *ContainerSpec) GetRootfsImageUrl() string {
	if x != nil {
		return x.RootfsImageUrl
	}
	return ""
}

func (x *ContainerSpec) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// DeployResponse indicates the result of a deployment attempt.
type DeployResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResponse) Reset() {
	*x = DeployResponse{}
	mi := &file_picobox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResponse) ProtoMessage() {}

func (x *DeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_picobox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResponse.ProtoReflect.Descriptor instead.
func (*DeployResponse) Descriptor() ([]byte, []int) {
	return file_picobox_proto_rawDescGZIP(), []int{5}
}

func (x *DeployResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *DeployResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeployResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_picobox_proto protoreflect.FileDescriptor

const file_picobox_proto_rawDesc = "" +
	"\n" +
	"\rpicobox.proto\x12\apicobox\"\x8f\x01\n" +
	"\fAgentMessage\x120\n" +
	"\ametrics\x18\x01 \x01(\v2\x14.picobox.NodeMetricsH\x00R\ametrics\x12B\n" +
	"\x0fdeploy_response\x18\x02 \x01(\v2\x17.picobox.DeployResponseH\x00R\x0edeployResponseB\t\n" +
	"\apayload\"\x9e\x01\n" +
	"\rMasterMessage\x12A\n" +
	"\rheartbeat_ack\x18\x01 \x01(\v2\x1a.picobox.HeartbeatResponseH\x00R\fheartbeatAck\x12?\n" +
	"\x0edeploy_request\x18\x02 \x01(\v2\x16.picobox.ContainerSpecH\x00R\rdeployRequestB\t\n" +
	"\apayload\"\xd1\x01\n" +
	"\vNodeMetrics\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12*\n" +
	"\x11cpu_usage_percent\x18\x02 \x01(\x02R\x0fcpuUsagePercent\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x04 \x01(\x04R\x10memoryTotalBytes\x12 \n" +
	"\fdisk_io_wait\x18\x05 \x01(\x02R\n" +
	"diskIoWait\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\xc4\x01\n" +
	"\rContainerSpec\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12(\n" +
	"\x10memory_max_bytes\x18\x02 \x01(\x04R\x0ememoryMaxBytes\x12\"\n" +
	"\rcpu_max_quota\x18\x03 \x01(\rR\vcpuMaxQuota\x12(\n" +
	"\x10rootfs_image_url\x18\x04 \x01(\tR\x0erootfsImageUrl\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\"r\n" +
	"\x0eDeployResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2U\n" +
	"\fAgentService\x12E\n" +
	"\x0eControlChannel\x12\x15.picobox.AgentMessage\x1a\x16.picobox.MasterMessage\"\x00(\x010\x01B6Z4github.com/henny-cho/picobox/internal/api/pb;picoboxb\x06proto3"

var (
	file_picobox_proto_rawDescOnce sync.Once
	file_picobox_proto_rawDescData []byte
)

func file_picobox_proto_rawDescGZIP() []byte {
	file_picobox_proto_rawDescOnce.Do(func() {
		file_picobox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_picobox_proto_rawDesc), len(file_picobox_proto_rawDesc)))
	})
	return file_picobox_proto_rawDescData
}

var file_picobox_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_picobox_proto_goTypes = []any{
	(*AgentMessage)(nil),      // 0: picobox.AgentMessage
	(*MasterMessage)(nil),     // 1: picobox.MasterMessage
	(*NodeMetrics)(nil),       // 2: picobox.NodeMetrics
	(*HeartbeatResponse)(nil), // 3: picobox.HeartbeatResponse
	(*ContainerSpec)(nil),     // 4: picobox.ContainerSpec
	(*DeployResponse)(nil),    // 5: picobox.DeployResponse
}
var file_picobox_proto_depIdxs = []int32{
	2, // 0: picobox.AgentMessage.metrics:type_name -> picobox.NodeMetrics
	5, // 1: picobox.AgentMessage.deploy_response:type_name -> picobox.DeployResponse
	3, // 2: picobox.MasterMessage.heartbeat_ack:type_name -> picobox.HeartbeatResponse
	4, // 3: picobox.MasterMessage.deploy_request:type_name -> picobox.ContainerSpec
	0, // 4: picobox.AgentService.ControlChannel:input_type -> picobox.AgentMessage
	1, // 5: picobox.AgentService.ControlChannel:output_type -> picobox.MasterMessage
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_picobox_proto_init() }
func file_picobox_proto_init() {
	if File_picobox_proto != nil {
		return
	}
	file_picobox_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Metrics)(nil),
		(*AgentMessage_DeployResponse)(nil),
	}
	file_picobox_proto_msgTypes[1].OneofWrappers = []any{
		(*MasterMessage_HeartbeatAck)(nil),
		(*MasterMessage_DeployRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_picobox_proto_rawDesc), len(file_picobox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_picobox_proto_goTypes,
		DependencyIndexes: file_picobox_proto_depIdxs,
		MessageInfos:      file_picobox_proto_msgTypes,
	}.Build()
	File_picobox_proto = out.File
	file_picobox_proto_goTypes = nil
	file_picobox_proto_depIdxs = nil
}
