name: PicoBox CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.1'
          cache: true

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Give execution permission to scripts
        run: chmod +x ./script/setup.sh ./script/build.sh ./script/build_n_test.sh

      - name: Run Environment Setup
        run: ./script/setup.sh

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.11.3
          working-directory: .

      - name: Run Validation Loop
        run: bash ./script/build_n_test.sh --fullstack
